on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.8.0 #needed?
    - uses: Hummingbird-RegTech/check-pr-body-action@v1 #can this be local path, too?
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        body_pattern: '(done|DONE)+'
          failure_message: 'Description cannot be empty!!'
          success_message: 'Pull Request Successful! Great job including a description!'
                    
#HOLD
#!/bin/bash

#STR='message'
#SUB='Done'
#if [[ "$STR" == *"$SUB"* ]]; then
   
#fi 

