name: Example workflow
on: [issues, pull_request]
jobs:
  example:
    name: RegEx Checker Job
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout 
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run fabiankoestring/body-regex-validator-action 
      uses: fabiankoestring/body-regex-validator-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_PATTERN: '.*((T|t)esting\s(D|d)one:).{5}.*' #'^(.*Description.*Changes.*Tests.*)$'
        PULL_REQUEST_COMMENT: 'This is my pr comment template.'
        ISSUE_PATTERN: '.*((T|t)esting\s(D|d)one:).{5}.*'
        ISSUE_COMMENT: 'This is my issue comment template.'
        failure_message: "Failed!" # to do: find out why this isn't showing somewhere
        success_message: "Success!"
