name: Example workflow
on:
  pull_request:
jobs:
  example:
    name: RegEx Checker Job
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout #let's see
      uses: actions/checkout@v1 #let's see
    - uses: Hummingbird-RegTech/check-pr-body-action@v1 #can this be local path, too?
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        body_pattern: '(done|DONE)+'
        failure_message: "Description cannot be empty!!"
        success_message: "Pull Request Successful! Great job including a description!"
