on:
  pull_request:
jobs:
  example:
    name: Webhook
    runs-on: ubuntu-latest

- name: Webhook POST Action
  uses: muinmomin/webhook-action@v1.0.0
  with:
    url: ${{ secrets.WEBHOOK_URL }}
    data: "{'command': 'publish'}"
