on:
  pull_request:

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: Hummingbird-RegTech/check-pr-body-action@v1 #can this be local path, too?
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        body_pattern: '(done|DONE)+'
        failure_message: "Description cannot be empty!!"
        success_message: "Pull Request Successful! Great job including a description!"
