name: Example workflow
on: [issues, pull_request]
jobs:
  example:
    name: Example job
    runs-on: ubuntu-latest
    steps:
    - name: Run actions/checkout 
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Run fabiankoestring/body-regex-validator-action 
      uses: fabiankoestring/body-regex-validator-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PULL_REQUEST_PATTERN: '.*((T|t)esting\s(D|d)one:).{5}.*)' #.*((T|t)esting\s(D|d)one:).{5}.*)
        PULL_REQUEST_COMMENT: 'Thank you for your code contribution!'
        ISSUE_PATTERN: '^(.*Description.*Behavior.*)$'
        ISSUE_COMMENT: 'Here is an issue. An issue is here.'
